name: eatnlift
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  firebase_app_check: ^0.3.1+4
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

